### ISSUE TITLE
OTA disabled

### ISSUE THREAD

**Issue by p13rr37** [dresden-elektronik/deconz-ota-plugin#7]
Deconz shows "OTA disabled" in the OTA Update panel and I see no way to activate it. My deconz runs on Home Assistant.
I can't query for firmware. When I click on query nothing is happening.

**Comment by ebaauw** [comment]
Enable OTAU under the _Advanced Settings_ of the _Settings_ page in the old web app.

**Comment by p13rr37** [comment]
> Enable OTAU under the _Advanced Settings_ of the _Settings_ page in the old web app.

Thanks for helping.
I don't know how to open the the old web app because I my Deconz runs on Home Assistant and I connect to Deconz via vnc. When I click on WebApp nothing happens (or at least I cant see it in the VNC client).

**Comment by magenbrot** [comment]
I'll add a hint on how to access the old UI since it took me some time to figure it out.

To access the old UI you need to enable the port for the API backend (40850) in the deconz supervisor configuration in Home Assistant. After saving restart the deconz container. You can now access the UI with http://<your-hass-ip>:40850/login.html
